chore: add back blunderbuss configs overridden by yoshi-automation
googleapis/java-errorreporting pull request #369
Opened 2021-01-20 21:03 UTC by nicoleczhu

2021-02-02 22:15 UTC, eaball35 approved these changes

2021-02-18 23:14 UTC, chingor13 requested changes
you're going to want to add an exclude to `synth.py` for this file.

2021-02-19 18:46 UTC, chingor13 commented
Here's an example exclude: https://github.com/googleapis/java-bigquerystorage/blob/master/synth.py#L38-L43

2021-06-16 18:14 UTC, simonz130 approved these changes

2021-06-16 18:14 UTC, closed without merging